[profile.default]
src = 'contracts'
out = 'out'
libs = [
    'lib'
]
ffi=true
verbosity=5
optimizer = true
optimizer_runs = 500

[profile.profilecompiler]
version = "0.8.0"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config